/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ancienttiles;

/**
 *
 * @author krr428
 */
public class GameInfoPanel extends javax.swing.JPanel
{

    private GameStateDisplayer aggrStateDisplayer;

    protected AbstractGameManager getModel()
    {
        return this.aggrStateDisplayer.model;
    }

    protected class InfoPanelDisplayer extends GameStateDisplayer
    {

        public InfoPanelDisplayer(AbstractGameManager underlyingModel)
        {
            super(underlyingModel);
            underlyingModel.getMapManager().addMapChangedListener(new AbstractGameManager.MapChangedListener() {

                @Override
                public void mapChanged()
                {
                    updateDisplay();
                }
            });
        }
        
        /*@Override
         * public void handleMapChanged()
         * {
         * updateDisplay();
         * }*/

        @Override
        public void updateDisplay()
        {
            GameInfoPanel.this.txtUserLocation.setText("(" + model.getHIManager().getHI().getX() + ", "
                    + model.getHIManager().getHI().getY() + ")");            
            
            inventoryPanel1.displayInventory(model.getHIManager().getHI().getInventoryMgr().getInventory());
            
            revalidate();
            repaint();
        }
    }

    /**
     * Creates new form GameInfoPanel
     */
    public GameInfoPanel(AbstractGameManager model)
    {
        initComponents();
        aggrStateDisplayer = new InfoPanelDisplayer(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        txtUserLocation = new javax.swing.JTextField();
        inventoryPanel1 = new ancienttiles.InventoryPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setRequestFocusEnabled(false);

        jLabel1.setText("User Location:");

        txtUserLocation.setEditable(false);
        txtUserLocation.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txtUserLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUserLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ancienttiles.InventoryPanel inventoryPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtUserLocation;
    // End of variables declaration//GEN-END:variables
}
