/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ancienttiles;

import ancienttiles.tiles.MainTileFactory;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author krr428
 */
public class InventoryPanel extends javax.swing.JPanel
{

    private static Tile bluekeyExample = null;
    private static Tile redkeyExample = null;
    private static Tile yellowkeyExample = null;
    private static Tile greenkeyExample = null;
    private static Tile barkcodexExample = null;

    /**
     * Creates new form InventoryPanel
     */
    public InventoryPanel()
    {
        initComponents();
        bluekeyExample = MainTileFactory.getInstance().getTile("key b");
        redkeyExample = MainTileFactory.getInstance().getTile("key r");
        greenkeyExample = MainTileFactory.getInstance().getTile("key g");
        yellowkeyExample = MainTileFactory.getInstance().getTile("key y");
        barkcodexExample = MainTileFactory.getInstance().getTile("barkcodex");

        displayInventory(new HashSet<Tile>());
    }

    public final void displayInventory(Set<Tile> items)
    {
        int bkey = 0;
        int rkey = 0;
        int ykey = 0;
        int gkey = 0;
        int barkcodex = 0;
        for (Tile t : items)
        {
            if (t.hasAttribute("bluekey"))
            {
                bkey++;
            }
            if (t.hasAttribute("redkey"))
            {
                rkey++;
            }
            if (t.hasAttribute("greenkey"))
            {
                gkey++;
            }
            if (t.hasAttribute("yellowkey"))
            {
                ykey++;
            }
            if (t.hasAttribute("barkcodex"))
            {
                barkcodex++;
            }
        }

        this.blueKeysDisplay.displayItems(bluekeyExample, bkey);
        this.redKeysDisplay.displayItems(redkeyExample, rkey);
        this.greenKeysDisplay.displayItems(greenkeyExample, gkey);
        this.yellowKeysDisplay.displayItems(yellowkeyExample, ykey);
        this.barkcodexDisplay.displayItems(barkcodexExample, barkcodex);

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        redKeysDisplay = new ancienttiles.NumericalInvItemDisplay();
        greenKeysDisplay = new ancienttiles.NumericalInvItemDisplay();
        blueKeysDisplay = new ancienttiles.NumericalInvItemDisplay();
        yellowKeysDisplay = new ancienttiles.NumericalInvItemDisplay();
        barkcodexDisplay = new ancienttiles.NumericalInvItemDisplay();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jTree1);

        setMaximumSize(new java.awt.Dimension(235, 2147483647));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(redKeysDisplay);
        add(greenKeysDisplay);
        add(blueKeysDisplay);
        add(yellowKeysDisplay);
        add(barkcodexDisplay);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ancienttiles.NumericalInvItemDisplay barkcodexDisplay;
    private ancienttiles.NumericalInvItemDisplay blueKeysDisplay;
    private ancienttiles.NumericalInvItemDisplay greenKeysDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private ancienttiles.NumericalInvItemDisplay redKeysDisplay;
    private ancienttiles.NumericalInvItemDisplay yellowKeysDisplay;
    // End of variables declaration//GEN-END:variables
}
