/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ancienttiles;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author krr428
 */
public class NumericalInvItemDisplay extends javax.swing.JPanel
{
    //This method does not do the filtering.  It will just get the picture
    // from the first item, then get the count of the rest.

    private int lastCount = 0;
    final private Border regularBorder;
    
    public void highlight(int type)
    {
        Color borderColor = null;
        if (type > 0)
        {
            borderColor = Color.YELLOW;
        }
        else if (type < 0)
        {
            borderColor = Color.RED;
        }        
        Border newBorder = BorderFactory.createLineBorder(borderColor, 2);
        this.setBorder(newBorder);
        Timer highlightExpire = new Timer(750, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                NumericalInvItemDisplay.this.setBorder(regularBorder);                
            }
        });
        
        highlightExpire.setRepeats(false);
        highlightExpire.start();
    }
    
    public void displayItems(Collection<Tile> similarItems)
    {
        displayItems(similarItems.iterator().next(), similarItems.size());
    }

    public void displayItems(Tile example, int count)
    {
        this.IconLabel.setText("");
        this.IconLabel.setIcon(new ImageIcon(example.getImage()));
        this.txtCount.setText(String.valueOf(count));
        if (count != lastCount)
        {
            highlight(count - lastCount);
            lastCount = count;
        }
    }

    /**
     * Creates new form NumericalInvItemDisplay
     */
    public NumericalInvItemDisplay()
    {
        initComponents();
        regularBorder = this.getBorder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        IconLabel = new javax.swing.JLabel();
        txtCount = new javax.swing.JTextField();

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("00");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ancienttiles/tiles/orange_grate.png"))); // NOI18N
        IconLabel.setText("bluekey");

        txtCount.setEditable(false);
        txtCount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCount.setText("00");
        txtCount.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCount, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(IconLabel)
                .addComponent(txtCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconLabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCount;
    // End of variables declaration//GEN-END:variables
}
